// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pystr_capitalize_
std::vector < std::string > pystr_capitalize_(std::vector < std::string > strs);
RcppExport SEXP pystr_pystr_capitalize_(SEXP strsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector < std::string > >::type strs(strsSEXP);
    __result = Rcpp::wrap(pystr_capitalize_(strs));
    return __result;
END_RCPP
}
// pystr_isalnum_
std::vector < bool > pystr_isalnum_(std::vector < std::string > strs);
RcppExport SEXP pystr_pystr_isalnum_(SEXP strsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector < std::string > >::type strs(strsSEXP);
    __result = Rcpp::wrap(pystr_isalnum_(strs));
    return __result;
END_RCPP
}
// pystr_isalpha_
std::vector < bool > pystr_isalpha_(std::vector < std::string > strs);
RcppExport SEXP pystr_pystr_isalpha_(SEXP strsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector < std::string > >::type strs(strsSEXP);
    __result = Rcpp::wrap(pystr_isalpha_(strs));
    return __result;
END_RCPP
}
// pystr_isnumeric_
std::vector < bool > pystr_isnumeric_(std::vector < std::string > strs);
RcppExport SEXP pystr_pystr_isnumeric_(SEXP strsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector < std::string > >::type strs(strsSEXP);
    __result = Rcpp::wrap(pystr_isnumeric_(strs));
    return __result;
END_RCPP
}
