# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pystr_capitalize_ <- function(strs) {
    .Call('pystr_pystr_capitalize_', PACKAGE = 'pystr', strs)
}

