# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pystr_capitalize_ <- function(strs) {
    .Call('pystr_pystr_capitalize_', PACKAGE = 'pystr', strs)
}

pystr_center_ <- function(strs, width, fillchar) {
    .Call('pystr_pystr_center_', PACKAGE = 'pystr', strs, width, fillchar)
}

pystr_count_ <- function(strs, sub, start, end) {
    .Call('pystr_pystr_count_', PACKAGE = 'pystr', strs, sub, start, end)
}

pystr_isalnum_ <- function(strs) {
    .Call('pystr_pystr_isalnum_', PACKAGE = 'pystr', strs)
}

pystr_isalpha_ <- function(strs) {
    .Call('pystr_pystr_isalpha_', PACKAGE = 'pystr', strs)
}

pystr_islower_ <- function(strs) {
    .Call('pystr_pystr_islower_', PACKAGE = 'pystr', strs)
}

pystr_isnumeric_ <- function(strs) {
    .Call('pystr_pystr_isnumeric_', PACKAGE = 'pystr', strs)
}

pystr_isupper_ <- function(strs) {
    .Call('pystr_pystr_isupper_', PACKAGE = 'pystr', strs)
}

pystr_lstrip_ <- function(strs, chars) {
    .Call('pystr_pystr_lstrip_', PACKAGE = 'pystr', strs, chars)
}

pystr_rstrip_ <- function(strs, chars) {
    .Call('pystr_pystr_rstrip_', PACKAGE = 'pystr', strs, chars)
}

